version: '3.8'

services:
  dbpostgre:
    image: postgres:latest
    container_name: postgres-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - pg-network

volumes:
  pg-data:

networks:
  pg-network:
    driver: bridge